-- Add Gender enum (safe if already exists)
DO $$ BEGIN
  CREATE TYPE "Gender" AS ENUM ('MALE', 'FEMALE', 'OTHER');
EXCEPTION WHEN duplicate_object THEN null;
END $$;

-- Add missing columns to User table (IF NOT EXISTS = safe on existing DBs)
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "gender"      "Gender";
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "displayName" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "bio"         TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "interests"   TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "education"   TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "zodiac"      TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "jobTitle"    TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "company"     TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "school"      TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "city"        TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "height"      INTEGER;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "avatarUrl"   TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "latitude"    DOUBLE PRECISION;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "longitude"   DOUBLE PRECISION;
