/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/swipe` | `/swipe`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profile/discover-settings` | `/profile/discover-settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profile/edit` | `/profile/edit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profile/settings` | `/profile/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/onboarding` | `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/welcome` | `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/chat/[matchId]` | `/chat/[matchId]`, params: Router.UnknownInputParams & { matchId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/swipe` | `/swipe`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/profile/discover-settings` | `/profile/discover-settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/profile/edit` | `/profile/edit`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/profile/settings` | `/profile/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/onboarding` | `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/welcome` | `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/chat/[matchId]` | `/chat/[matchId]`, params: Router.UnknownOutputParams & { matchId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/chat${`?${string}` | `#${string}` | ''}` | `/chat${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(app)'}${'/(tabs)'}/swipe${`?${string}` | `#${string}` | ''}` | `/swipe${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/profile/discover-settings${`?${string}` | `#${string}` | ''}` | `/profile/discover-settings${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/profile/edit${`?${string}` | `#${string}` | ''}` | `/profile/edit${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/profile/settings${`?${string}` | `#${string}` | ''}` | `/profile/settings${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/onboarding${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/register${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/welcome${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/chat` | `/chat`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}${'/(tabs)'}/swipe` | `/swipe`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profile/discover-settings` | `/profile/discover-settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profile/edit` | `/profile/edit`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/profile/settings` | `/profile/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/onboarding` | `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/register` | `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/welcome` | `/welcome`; params?: Router.UnknownInputParams; } | `${'/(app)'}/chat/${Router.SingleRoutePart<T>}` | `/chat/${Router.SingleRoutePart<T>}` | { pathname: `${'/(app)'}/chat/[matchId]` | `/chat/[matchId]`, params: Router.UnknownInputParams & { matchId: string | number; } };
    }
  }
}
